---
abstract: 'fetch random image from'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-DoingItWrongCom-RandImage
provides:
  WWW::DoingItWrongCom::RandImage:
    file: lib/WWW/DoingItWrongCom/RandImage.pm
    version: 1.01
requires:
  Carp: 1.04
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  URI: 1.35
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
